filtered_jobs_url : "https://app.joinhandshake.com/stu/postings?page=1&per_page=25&sort_direction=desc&sort_column=default&job.job_types%5B%5D=3&job.remote=true&employment_type_names%5B%5D=Part-Time"

application:
  resume_path: "./assets/resume.pdf"
  cover_letter_path: "./assets/cover_letter.pdf"