filters:
  remote: true
  part_time:
    min_hours: 5
    max_hours: 20
  job_types:
    - Internship
    - Co-op

application:
  resume_path: "./assets/resume.pdf"
  cover_letter_path: "./assets/cover_letter.pdf"